### ISSUE TITLE
无法转移“电影”到媒体库

### ISSUE THREAD

**Issue by keeper-0** [developer-wlj/Windows-MoviePilot#20]
无论是自动运行还是之后的手动整理，均无法整理电影文件，但是电视剧是正常运行的。

以下是日志节选

【ERROR】2024-07-18 22:31:21,325 - transfer.py - 文件转移模块运行失败
【INFO】2024-07-18 22:31:21,324 - command.py - 处理事件：system.error - []

jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endif'.
  File "<unknown>", line 1, in template
    raise rewrite_traceback_stack(source=source)
  File "C:\Program Files (x86)\MoviePilot\Python3.11\Lib\site-packages\jinja2\environment.py", line 939, in handle_exception
    self.handle_exception(source=source_hint)
  File "C:\Program Files (x86)\MoviePilot\Python3.11\Lib\site-packages\jinja2\environment.py", line 768, in compile
                               ^^^^^^^^^^^^^^^^^^^^
    return cls.from_code(self, self.compile(source), gs, None)
  File "C:\Program Files (x86)\MoviePilot\Python3.11\Lib\site-packages\jinja2\environment.py", line 1108, in from_string
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    return env.from_string(source, template_class=cls)
  File "C:\Program Files (x86)\MoviePilot\Python3.11\Lib\site-packages\jinja2\environment.py", line 1211, in __new__
               ^^^^^^^^^^^^^^^^^^^^^^^^^
    template = Template(template_string)
  File "C:\Program Files (x86)\MoviePilot\project\MoviePilot\app\modules\filetransfer\__init__.py", line 717, in get_rename_path
               ^^^^^^^^^^^^^^^^^^^^^
    new_file = self.get_rename_path(
  File "C:\Program Files (x86)\MoviePilot\project\MoviePilot\app\modules\filetransfer\__init__.py", line 545, in transfer_media
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    return self.transfer_media(in_path=path,
  File "C:\Program Files (x86)\MoviePilot\project\MoviePilot\app\modules\filetransfer\__init__.py", line 153, in transfer
             ^^^^^^^^^^^^^^^^^^^^^
    result = func(*args, **kwargs)
  File "C:\Program Files (x86)\MoviePilot\project\MoviePilot\app\chain\__init__.py", line 107, in run_module
Traceback (most recent call last):
【ERROR】2024-07-18 22:31:21,316 - chain - 运行模块 FileTransferModule.transfer 出错：Encountered unknown tag 'endif'.
【INFO】2024-07-18 22:31:21,310 - filetransfer - 获取转移目标路径：C:\Users\wuti\Videos\softlink\movie
【INFO】2024-07-18 22:31:21,301 - transfer.py - [深海].Deep.Sea.2023.2160p.WEB-DL.HEVC.10bit.DV.DTS5.1.5Audios-QHstudIo.mp4 识别为：电影 深海 (2023)
【INFO】2024-07-18 22:31:21,290 - media.py - [深海].Deep.Sea.2023.2160p.WEB-DL.HEVC.10bit.DV.DTS5.1.5Audios-QHstudIo.mp4 识别到媒体信息：电影 深海 (2023)
【INFO】2024-07-18 22:31:21,286 - themoviedb - Deep Sea TMDB识别结果：电影 深海 (2023) 667717
【INFO】2024-07-18 22:31:21,269 - themoviedb - Deep Sea 使用TMDB识别缓存：深海
【INFO】2024-07-18 22:31:21,255 - transfer.py - 手动转移：D:\movie\动画电影\[深海].Deep.Sea.2023.2160p.WEB-DL.HEVC.10bit.DV.DTS5.1.5Audios-QHstudIo\[深海].Deep.Sea.2023.2160p.WEB-DL.HEVC.10bit.DV.DTS5.1.5Audios-QHstudIo.mp4 ...

**Comment by keeper-0** [comment]
找到问题了，我修改命名方式的时候多写了一个'endif‘,太糊涂了QAQ。
